SUPABASE_URL = "https://ixsdtxynqmmipwzcqbbw.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4c2R0eHlucW1taXB3emNxYmJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM4NDkzNzQsImV4cCI6MjA4OTQyNTM3NH0.6LsCPvUO0TbVrZzhQcjceH82EI14balhYVwMUfDJIsE"

